### ISSUE TITLE
uninitialized constant Angular (NameError)

### ISSUE THREAD

**Issue by gonzotim** [kikonen/capybara-ng#11]
I'm getting the following when I use capybara-ng

    /Users/myuser/legion/spec/spec_helper.rb:19:in `block in <top (required)>': uninitialized constant Angular (NameError)
	from /Users/myuser/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core.rb:81:in `configure'
	from /Users/myuser/legion/spec/spec_helper.rb:18:in `<top (required)>'
	from /Users/myuser/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `require'
	from /Users/myuser/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `block in requires='
	from /Users/myuser/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `each'
	from /Users/myuser/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1072:in `requires='
	from /Users/myuser/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:103:in `block in process_options_into'
	from /Users/myuser/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:102:in `each'
	from /Users/myuser/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:102:in `process_options_into'
	from /Users/myuser/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration_options.rb:22:in `configure'
	from /Users/myuser/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:95:in `setup'
	from /Users/myuser/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84:in `run'
	from /Users/myuser/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
	from /Users/myuser/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
	from /Users/myuser/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'
	from /Users/myuser/.rbenv/versions/2.1.5/bin/rspec:23:in `load'
	from /Users/myuser/.rbenv/versions/2.1.5/bin/rspec:23:in `<main>'

gemfile

    group :test do
      gem "factory_girl_rails"
      gem "capybara"
      gem 'capybara-ng'
      gem "guard-rspec"
      gem 'vcr'
      gem 'webmock'
      gem 'database_cleaner'
      gem 'launchy'
      gem 'capybara-email'
      gem 'timecop'
    end

spec_helper.rb
```
RSpec.configure do |config|
  config.include ::Angular::DSL
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

=begin
  config.filter_run :focus
  config.run_all_when_everything_filtered = true

  config.disable_monkey_patching!

  if config.files_to_run.one?
    config.default_formatter = 'doc'
  end

  config.profile_examples = 10

  config.order = :random
  Kernel.srand config.seed
=end
end
```

Thanks in advance

**Comment by kikonen** [comment]
Is require for capara-ng is in spec helper?

@see https://github.com/kikonen/host/blob/master/spec/rails_helper.rb

**Comment by gonzotim** [comment]
Hi Kari, I tried adding the require - same issue. Thanks.

**Comment by kikonen** [comment]
That is weird, if require is there then it should work, since error is clearly due to missing module, which is the one from the gem.

**Comment by kikonen** [comment]
Are you able to provide whole spec_helper.rb file?

**Comment by andrewlphilpott** [comment]
Was this ever solved? I'm running into the same issue.

**Comment by kikonen** [comment]
If you are able to provide details then there is changes :)

**Comment by andrewlphilpott** [comment]
I actually went another route, so I'm all set. Thanks, though!
