### ISSUE TITLE
ng_wait error

### ISSUE THREAD

**Issue by mduqueoviedo** [kikonen/capybara-ng#12]
This is an awesome gem, full of potential! But...

On a simple test I am getting this error:

```
Failure/Error: ng_wait
     NoMethodError:
       undefined method `size' for :FN_waitForAngular:Symbol
     # /home/vagrant/.rvm/gems/ruby-2.2.0/gems/capybara-ng-0.2.1/lib/angular/client_script.rb:769:in `block in functions'
     # /home/vagrant/.rvm/gems/ruby-2.2.0/gems/capybara-ng-0.2.1/lib/angular/client_script.rb:768:in `map'
     # /home/vagrant/.rvm/gems/ruby-2.2.0/gems/capybara-ng-0.2.1/lib/angular/client_script.rb:768:in `functions'
     # /home/vagrant/.rvm/gems/ruby-2.2.0/gems/capybara-ng-0.2.1/lib/angular/client_script.rb:789:in `window_scripts'
     # /home/vagrant/.rvm/gems/ruby-2.2.0/gems/capybara-ng-0.2.1/lib/angular/setup.rb:109:in `install'
     # /home/vagrant/.rvm/gems/ruby-2.2.0/gems/capybara-ng-0.2.1/lib/angular/setup.rb:12:in `ng_wait'
     # /home/vagrant/.rvm/gems/ruby-2.2.0/gems/capybara-ng-0.2.1/lib/angular/dsl.rb:41:in `ng_wait'
     # ./spec/features/login_spec.rb:9:in `block (2 levels) in <top (required)>'```
```

My test starts with:

```
scenario "Show ", js: true do
    select_page = select_bank_page

    ng_wait

```

I am including everything which is required and checked your examples too.
Any clue?

**Comment by kikonen** [comment]
Looks like small showstopper issue. My first guess is that behavior change between ruby 2.1 and 2.2 triggers issue.

**Comment by kikonen** [comment]
didn't have time yesterday to look into this. But now there is capybara-ng v0.2.2.

Could you try and see if you encounter problem with it.

**Comment by mduqueoviedo** [comment]
Thank you very much for answering that fast! I will test it on Monday and let you know :)

**Comment by mduqueoviedo** [comment]
Thank you very much, it is not throwing any error now.
