### ISSUE TITLE
Failure in ng_wait

### ISSUE THREAD

**Issue by rtcoms** [kikonen/capybara-ng#17]
I'm using capybara with poltergeist geckodriver .

Have Following  rspec 

```
require 'rails_helper'

RSpec.describe "Article Listing", type: :feature, js: true do
  include Angular::DSL

  context "when viewed by a site admin" do
    before do
      create(:published_article)
      sign_in_as_a_site_admin
      visit '/articles/browse'
      ng_wait
    end

    it "should list articles" do
      wait_for_ajax
      expect(page).to have_content('topic channel') 
    end
  end

end
```

and getting error

```
Failure/Error: ng_wait
     Selenium::WebDriver::Error::UnknownError:
       Failed to find value field

# /Users/rtcoms/.rvm/gems/ruby-2.2.1@learninglabs/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
     # /Users/rtcoms/.rvm/gems/ruby-2.2.1@learninglabs/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
     # /Users/rtcoms/.rvm/gems/ruby-2.2.1@learninglabs/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/common.rb:81:in `new'
     # /Users/rtcoms/.rvm/gems/ruby-2.2.1@learninglabs/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/common.rb:81:in `create_response'
     # /Users/rtcoms/.rvm/gems/ruby-2.2.1@learninglabs/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/default.rb:86:in `request'
     # /Users/rtcoms/.rvm/gems/ruby-2.2.1@learninglabs/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
     # /Users/rtcoms/.rvm/gems/ruby-2.2.1@learninglabs/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/w3c_bridge.rb:659:in `raw_execute'
     # /Users/rtcoms/.rvm/gems/ruby-2.2.1@learninglabs/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/w3c_bridge.rb:634:in `execute'
     # /Users/rtcoms/.rvm/gems/ruby-2.2.1@learninglabs/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/remote/w3c_bridge.rb:365:in `execute_script'
     # /Users/rtcoms/.rvm/gems/ruby-2.2.1@learninglabs/gems/selenium-webdriver-3.0.1/lib/selenium/webdriver/common/driver.rb:215:in `execute_script'
     # /Users/rtcoms/.rvm/gems/ruby-2.2.1@learninglabs/gems/capybara-2.4.4/lib/capybara/selenium/driver.rb:84:in `evaluate_script'
     # /Users/rtcoms/.rvm/gems/ruby-2.2.1@learninglabs/gems/capybara-2.4.4/lib/capybara/session.rb:527:in `evaluate_script'
     # /Users/rtcoms/.rvm/gems/ruby-2.2.1@learninglabs/gems/capybara-ng-0.2.7/lib/angular/setup.rb:110:in `block in install'
     # /Users/rtcoms/.rvm/gems/ruby-2.2.1@learninglabs/gems/capybara-ng-0.2.7/lib/angular/setup.rb:109:in `each'
     # /Users/rtcoms/.rvm/gems/ruby-2.2.1@learninglabs/gems/capybara-ng-0.2.7/lib/angular/setup.rb:109:in `install'
     # /Users/rtcoms/.rvm/gems/ruby-2.2.1@learninglabs/gems/capybara-ng-0.2.7/lib/angular/setup.rb:12:in `ng_wait'
     # /Users/rtcoms/.rvm/gems/ruby-2.2.1@learninglabs/gems/capybara-ng-0.2.7/lib/angular/setup.rb:66:in `make_call'
     # /Users/rtcoms/.rvm/gems/ruby-2.2.1@learninglabs/gems/capybara-ng-0.2.7/lib/angular/dsl.rb:52:in `ng_location_abs'
     # ./spec/features/articles/article_listing_spec.rb:18:in `block (3 levels) in <top (required)>'
```

Not sure if issue is related to capybara-ng or selenium. None of the capybara-ng DSL is working , Although is rendering find without capybara-ng by using wait for ajax.

**Comment by kikonen** [comment]
Surely it can't work if it fails to "install" js scripts into browser. However, I did run tests in project and they succeed with "selenium" driver. So not sure what's going wrong.

Are you able to attach log/test.log?

**Comment by kikonen** [comment]
Q: Are you able to try with another driver, like poltergeist?

**Comment by rtcoms** [comment]
Sorry my bad , I actually tried this with poltergeist only , but not sure why in logs it shows issue with selenium , I will post test.log in a while

**Comment by rtcoms** [comment]
Well, I;ve sorted out the issue. Looks like it was related to poltergeist timeout. I increased the timeout perios and it started working.

Thanks . Closing the issue .
