### ISSUE TITLE
Undefined method `seconds' for 2:Fixnum

### ISSUE THREAD

**Issue by giovanicosta** [kikonen/capybara-ng#18]
C:\dev\workspace\iautomation (master)
λ cucumber features\specifications\agco_implementsapp\login.feature
undefined method `seconds' for 2:Fixnum
Did you mean?  send (NoMethodError)
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/capybara-ng-0.2.7/lib/angular.rb:6:in `<module:Angular>'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/capybara-ng-0.2.7/lib/angular.rb:5:in `<top (required)>'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/capybara-ng-0.2.7/lib/capybara-ng.rb:1:in `require_relative'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/capybara-ng-0.2.7/lib/capybara-ng.rb:1:in `<top (required)>'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
C:/dev/workspace/iautomation/features/support/env.rb:6:in `<top (required)>'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load_code_file'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:142:in `load_file'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:84:in `block in load_files!'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `each'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `load_files!'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:253:in `load_step_definitions'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:61:in `run!'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
C:/Ruby23-x64/bin/cucumber:22:in `load'
C:/Ruby23-x64/bin/cucumber:22:in `<main>'

Please @kikonen, can you help me?

**Comment by kikonen** [comment]
If "2.seconds" is failing it's indication that rails activesupport gem providing that extension is not loaded.

```ruby
require 'activesupport'
```

However, since gem is built with assumption of rails environment this is likely not only case were some rails dependency is hit.

**Comment by giovanicosta** [comment]
Thanks for the feedback @kikonen. I stated in *features/support/env.rb*, but unsuccessfully 
as follows:

`C:\dev\workspace\iautomation (master)                                                                                  
λ cucumber features\specifications\implementsapp\login.feature                                                    
cannot load such file -- activesupport (LoadError)                                                                     
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'                             
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'                             
C:/dev/workspace/iautomation/features/support/env.rb:6:in `<top (required)>'                                           
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load'              
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load_code_file'    
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:142:in `load_file'          
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:84:in `block in load_files!'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `each'                
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `load_files!'         
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:253:in `load_step_definitions'           
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:61:in `run!'                             
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'                        
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'                             
C:/Ruby23-x64/bin/cucumber:22:in `load'                                                                                
C:/Ruby23-x64/bin/cucumber:22:in `<main>'
`
`C:\dev\workspace\iautomation (master)
λ gem list --local

*** LOCAL GEMS ***

...
activesupport (5.0.1, 5.0.0.1)`
...

**Comment by kikonen** [comment]
require 'active_support'

Hmm.. was it with underscore. I always forget, since gem naming and needed require had some inconsistencies in rails gems

**Comment by giovanicosta** [comment]
Thank you. But, the same problem as follow:

`C:\dev\workspace\iautomation (master)
λ cucumber features\specifications\implementsapp\login.feature
undefined method `seconds' for 2:Fixnum
Did you mean?  send (NoMethodError)
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/capybara-ng-0.2.7/lib/angular.rb:6:in `<module:Angular>'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/capybara-ng-0.2.7/lib/angular.rb:5:in `<top (required)>'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/capybara-ng-0.2.7/lib/capybara-ng.rb:1:in `require_relative'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/capybara-ng-0.2.7/lib/capybara-ng.rb:1:in `<top (required)>'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
C:/dev/workspace/iautomation/features/support/env.rb:7:in `<top (required)>'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load_code_file'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:142:in `load_file'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:84:in `block in load_files!'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `each'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `load_files!'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:253:in `load_step_definitions'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:61:in `run!'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
C:/Ruby23-x64/bin/cucumber:22:in `load'
C:/Ruby23-x64/bin/cucumber:22:in `<main>'`

![env_rb](https://cloud.githubusercontent.com/assets/11506494/22474463/fd4f4e2c-e7c2-11e6-97d2-675e6aeabeeb.png)
![project](https://cloud.githubusercontent.com/assets/11506494/22474462/fd4f41fc-e7c2-11e6-96a6-2d6bb6c4754b.png)
![step_definition_rb](https://cloud.githubusercontent.com/assets/11506494/22474464/fd53fddc-e7c2-11e6-9dda-4d342e36c447.png)

**Comment by kikonen** [comment]
http://stackoverflow.com/questions/4238867/how-do-i-use-active-support-core-extensions

```ruby
require 'active_support/all'
```
